FROM freqtradeorg/freqtrade:2021.11
COPY exchange.py freqtrade/exchange/exchange.py
COPY ftx.py freqtrade/freqtrade/exchange/ftx.py
COPY IPairList.py freqtrade/plugins/pairlist/IPairList.py

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# The below dependency - pyti - serves as an example. Please use whatever you need!
#RUN pip install --user pyti
RUN pip install py3cw
# USER ftuser 
